config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/migration_status", to: "homes#migration_status"
  post "/", to: "homes#index"
  root to: "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/random_value.rb
# == Schema Information
#
# Table name: random_values
#
#  id           :bigint           not null, primary key
#  value        :float
#  generated_at :datetime
#

class RandomValue < ApplicationRecord
  validates :value, presence: true
  validates :generated_at, presence: true

  def self.average_in_range(start_date, end_date)
    values = RandomValue.where("generated_at BETWEEN ? AND ?", start_date, end_date).pluck(:value)

    return nil unless values.any?
    values.reduce(&:+) / values.count
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    if params[:start_time] && params[:end_time]
      start_time = Time.new(*params[:start_time].values)
      end_time = Time.new(*params[:end_time].values)
      @average = RandomValue.average_in_range(start_time, end_time)
    end
  end

  def migration_status
    @migration_data = MigrationStatus.status
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
<%= form_tag root_path do %>
  <div class="form-group">
    <label>Start Time</label>
    <%= datetime_select :start_time, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>End Time</label>
    <%= datetime_select :end_time, nil, class: "form-control" %>
  </div>
  <%= submit_tag "Submit" %>
<% end %>

<% if request.method == "POST" %>
  <div class="row">
    <div class="col-4 ml-auto mr-auto">
      <div class="card">
        <div class="card-header">Average</div>
        <div class="card-body text-center">
          <%= @average ? @average : "No data returned" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/homes/migration_status.html.erb
<h1>Migration Status</h1>

<table class="table">
  <thead>
    <tr>
      <th>Status</th>
      <th>ID</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @migration_data.each do |data| %>
      <tr>
        <% data.each do |item| %>
          <td><%= item %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Random Numbers", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link" do %>
            Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to migration_status_path, class: "nav-link" do %>
            Migration Status
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
            Sign Out
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            Sign In
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            Sign Up
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomNumbers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>